### ISSUE TITLE
how to use it

### ISSUE THREAD

**Issue by nobody0101** [iina/homebrew-mpv-iina#1]
hi,  how to run this script ?  ruby xxx.rb and some error happened

**Comment by saagarjha** [comment]
These are Homebrew taps for installing IINA's dependencies. Are you trying to do anything in particular?

**Comment by nobody0101** [comment]
I want to learn iina and join it, it is a great player
by the way, iina compile with xcode10.2, then the mpv will has an error occur, I should compile mpv myself ? xcode10 is ok

**Comment by saagarjha** [comment]
We're tracking this issue at https://github.com/iina/iina/issues/2439. It also links to instructions on how to use this repository to compile mpv, if you're using Homebrew.

**Comment by nobody0101** [comment]
very great work, thank you
